const products = [
  {
    id: 1,
    name: "ghee",
    size: 315,
    mu: "gr",
    cost: 11017,
    price: 26000,
    // rawMaterials: [
    //   {
    //     id: 1,
    //     name: "mantequilla",
    //     mu: "gr",
    //     quantity: 386.03,
    //     unitCost: 18,
    //     totalCost: 6948.53,
    //   },
    //   {
    //     id: 2,
    //     name: "envas",
    //     mu: "c/u",
    //     quantity: 1,
    //     unitCost: 2100,
    //     totalCost: 2100,
    //   },
    //   {
    //     id: 3,
    //     name: "etiqueta frasco",
    //     mu: "c/u",
    //     quantity: 1,
    //     unitCost: 289.86,
    //     totalCost: 289.86,
    //   },
    // ],
  },
  {
    id: 2,
    name: "ghee",
    size: 160,
    mu: "gr",
    cost: 6079,
    price: 14000,
  },
  {
    id: 3,
    name: "crema marañon",
    size: 400,
    mu: "gr",
    cost: 26355,
    price: 53000,
  },
  {
    id: 4,
    name: "crema marañon",
    size: 200,
    mu: "gr",
    cost: 13683,
    price: 30000,
  },
  {
    id: 5,
    name: "crema almendra",
    size: 400,
    mu: "gr",
    cost: 19899,
    price: 46000,
  },
  {
    id: 6,
    name: "crema almendra",
    size: 200,
    mu: "gr",
    cost: 10437,
    price: 27000,
  },
];
